# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 2.7
python: 3.7

# Install the codecov pip dependency
install:
  - pip install flake8

# Run the unit test
script:
  - flake8 --count
