name: ds-flow
channels:
  - defaults
dependencies:
  - python=3.6
  - pandas=0.24
  - numpy=1.15
  - jupyter=1.0
  - requests=2.21
  - flake8=3.7
  - pip:
    - scikit-learn==0.20
    - python-dotenv==0.10
